import './globals.css'
import Navbar from './navbar'

export const metadata = {
  title: 'Panverse website',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) 
{
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
